### ISSUE TITLE
A propos du format de la date

### ISSUE THREAD

**Issue by Amiralgaby** [thib1984/pyweatherfr#1]
Bonjour,

Le format du tableau est sympa. (tout le logiciel est bien ^^)
Pour les dates, j'avais pensé à un autre format (oui les points m'ont pertubé en premier x)

**Avant**
|15.11.2021 (Lun.)|🌤  Eclaircies |    2° -> 10°     |    0mm       |
|-----------------|--------------|------------------|--------------|
|16.11.2021 (Mar.)|🌞 Ensoleillé |    1° -> 10°     |    0mm       |
|17.11.2021 (Mer.)|🌤  Eclaircies |🧊  0° -> 7°      |💧  0.3mm     |
|18.11.2021 (Jeu.)|🌞 Ensoleillé |    2° -> 9°      |💧  0.1mm     |
|19.11.2021 (Ven.)|🌞 Ensoleillé |🧊  0° -> 11°     |    0mm       |

**Après**
|lun. 15 nov.|🌤  Eclaircies |    2° -> 10°     |    0mm       |
|-----------------|--------------|------------------|--------------|
|mar. 16 nov.|🌞 Ensoleillé |    1° -> 10°     |    0mm       |
|mer. 17 nov.|🌤  Eclaircies |🧊  0° -> 7°      |💧  0.3mm     |
|jeu. 18 nov.|🌞 Ensoleillé |    2° -> 9°      |💧  0.1mm     |
|ven 19 nov.|🌞 Ensoleillé |🧊  0° -> 11°     |    0mm       |

Que pense-tu de mettre les mois en lettres ?

Bonne journée

**Comment by thib1984** [comment]
Hello, bonne idée, je le note pour une version future!

**Comment by thib1984** [comment]
J'ai pour le moment réalisé une première étape accessible en version 1.4.2
17.11.2021 22:00 -> 17/11/2021 22:00
17.11.2021 (Mer.) -> Mer. 17/11/2021 (dans les tableaux)
